# Generated by Django 4.0.5 on 2022-08-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackx', '0002_investor_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterp',
            name='cfunds',
            field=models.CharField(default='Not Shared Yet', max_length=1000),
        ),
        migrations.AddField(
            model_name='enterp',
            name='field',
            field=models.CharField(default='General', max_length=1000),
        ),
        migrations.AddField(
            model_name='enterp',
            name='onldesc',
            field=models.CharField(default='Not Shared Yet', max_length=1000),
        ),
        migrations.AddField(
            model_name='enterp',
            name='qpitch',
            field=models.CharField(default='Not Shared Yet', max_length=1000),
        ),
        migrations.AddField(
            model_name='enterp',
            name='rfunding',
            field=models.CharField(default='Not Shared Yet', max_length=1000),
        ),
        migrations.AddField(
            model_name='investor',
            name='comphold',
            field=models.CharField(default='Not Shared Yet', max_length=1000),
        ),
        migrations.AddField(
            model_name='investor',
            name='doifield',
            field=models.CharField(default='General', max_length=1000),
        ),
        migrations.AddField(
            model_name='investor',
            name='networth',
            field=models.CharField(default='Not Shared Yet', max_length=1000),
        ),
    ]
