# Generated by Django 4.0.5 on 2022-08-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackx', '0003_enterp_cfunds_enterp_field_enterp_onldesc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='doifield',
            new_name='invfield',
        ),
    ]
